# Generated by Django 5.2.5 on 2025-11-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_contact_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, choices=[('road', 'Road'), ('water', 'Water'), ('electricity', 'Electricity'), ('garbage', 'Garbage'), ('sewage', 'Sewage'), ('lighting', 'Street Lighting'), ('pollution', 'Pollution'), ('traffic', 'Traffic')], help_text='Required only if role = provider', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('provider', 'Provider')], default='consumer', max_length=20),
        ),
    ]
