# Generated by Django 5.2.5 on 2025-11-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('road', 'Road Maintenance'), ('water', 'Water Supply'), ('garbage', 'Garbage & Sanitation'), ('drainage', 'Drainage & Sewage'), ('street_light', 'Street Lighting')], help_text='Required only if role = provider', max_length=50, null=True),
        ),
    ]
