# Generated by Django 5.2.5 on 2025-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_contact_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, choices=[('road', 'Road Maintenance'), ('garbage', 'Garbage & Sanitation'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('drainage', 'Drainage & Sewage'), ('street_light', 'Street Lighting'), ('pollution', 'Pollution'), ('traffic', 'Traffic'), ('other', 'Other')], help_text='Required only if role = provider', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('provider', 'Provider')], default='consumer', help_text='User role: consumer or provider', max_length=20),
        ),
    ]
