# Generated by Django 5.2.5 on 2026-01-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_contact_alter_customuser_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, choices=[('road', 'Road Maintenance'), ('garbage', 'Garbage & Sanitation'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('drainage', 'Drainage & Sewage'), ('street_light', 'Street Lighting'), ('pollution', 'Pollution'), ('traffic', 'Traffic'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('provider', 'Provider')], default='consumer', max_length=20),
        ),
    ]
