# Generated by Django 5.2.4 on 2025-08-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_issue_options_issue_additional_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
