# Generated by Django 5.2.5 on 2025-08-20 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_flagreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='additional_photos',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('road', 'Road'), ('garbage', 'Garbage'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('sewage', 'Sewage'), ('lighting', 'Street Lighting'), ('pollution', 'Pollution'), ('traffic', 'Traffic'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='flagreport',
            unique_together={('issue', 'reported_by')},
        ),
        migrations.CreateModel(
            name='IssuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='issue_photos/extra/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.issue')),
            ],
        ),
    ]
