# Generated by Django 5.2.5 on 2025-08-22 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_issue_additional_photos_alter_issue_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
