# Generated by Django 5.2.5 on 2025-11-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_issue_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, choices=[('road', 'Road'), ('garbage', 'Garbage'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('sewage', 'Sewage'), ('lighting', 'Street Lighting'), ('pollution', 'Pollution'), ('traffic', 'Traffic'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
