# Generated by Django 5.2.5 on 2026-03-16 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_flagreport_options_remove_issue_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, choices=[('road', 'Road'), ('garbage', 'Garbage'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('drainage', 'Drainage & Sewage'), ('street_light', 'Street Lighting'), ('pollution', 'Pollution'), ('traffic', 'Traffic'), ('other', 'Other')], help_text='Auto-filled by ML after creation if empty', max_length=50, null=True),
        ),
    ]
